Improve launcher script for activemq
Use our standard puppet/init script

diff --git a/SOURCES/start-activemq-console b/SOURCES/start-activemq-console
--- a/SOURCES/start-activemq-console
+++ b/SOURCES/start-activemq-console
@@ -1,3 +1,63 @@
-#!
-java -Dactivemq.home=PREFIX -Dactivemq.base=PREFIX -Dcom.sun.management.jmxremote -Dorg.apache.activemq.UseDedicatedTaskRunner=false -Xmx512m -Djava.library.path=/usr/lib:/usr/lib64 -classpath  PREFIX/bin/activemq.jar org.apache.activemq.console.Main start
+#!/bin/sh
+
+dir="PREFIX"
+user="activemq"
+cmd="java -Dactivemq.home=PREFIX -Dactivemq.base=PREFIX -Dcom.sun.management.jmxremote -Dorg.apache.activemq.UseDedicatedTaskRunner=false -Xmx512m -Djava.library.path=/usr/lib:/usr/lib64 -classpath  PREFIX/bin/activemq.jar org.apache.activemq.console.Main start"
+
+name=`basename $0`
+pid_file="PREFIX/run/$name.pid"
+stdout_log="PREFIX/log/$name.log"
+stderr_log="PREFIX/log/$name.err"
+
+get_pid() {
+    cat "$pid_file"    
+}
+
+is_running() {
+    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
+}
+
+case "$1" in
+    start)
+	if is_running; then
+	    echo "Already started"
+	else
+	    echo "Starting $name"
+	    cd "$dir"
+            sudo -u "$user" $cmd > "$stdout_log" 2> "$stderr_log" \
+		& echo $! > "$pid_file"
+	    if ! is_running; then
+		echo "Unable to start, see $stdout_log and $stderr_log"
+		exit 1
+	    fi
+	fi
+	;;
+    stop)
+	if is_running; then
+	    echo "Stopping $name"
+	    kill `get_pid`
+	    rm "$pid_file"
+	else
+	    echo "Not running"
+	fi
+	;;
+    restart)
+	$0 stop
+	$0 start
+	;;
+    status)
+	if is_running; then
+	    echo "Running"
+	else
+	    echo "Stopped"
+	    exit 1
+	fi
+	;;
+    *)
+	echo "Usage: $0 {start|stop|restart|status}"
+	exit 1
+	;;
+esac
+
+exit 0
 
